;**********************************************************************
;                                                                     *
;    Filename:	    lcdlib.inc                                        *
;    Date:                                                            *
;    Author:        el@jap.hu                                         *
;    Www page:      http://jap.hu/electronic/                         *
;                                                                     *
;**********************************************************************

	EXTERN lcd_init, lcd_strout, lcd_decout, lcd_hexout, lcd_cmdout
	EXTERN lcd_chrout, lcd_delay5ms
	GLOBAL messages